### ISSUE TITLE
IE11 doesn't suggest to save password.

### ISSUE THREAD

**Issue by JelleDekker** [mendix/LoginForm#6]
Using the LoginForm plugin, IE11 never seems to suggest to save the password, while it does do this for other websites. And using the LoginForm, other browser do suggest to save the password. Does anyone know why this is?

**Comment by tieniber** [comment]
For IE10, I found [this info](https://blogs.msdn.microsoft.com/ieinternals/2009/09/10/why-wont-ie-remember-my-login-info/).

Because the widget submit the form via JS and not a standard form submit, it looks like they recommend that you call [this function](https://msdn.microsoft.com/en-us/library/Aa744113.aspx) to save form details

**Comment by Da-Dude** [comment]
@tieniber Did you manage to get this to work at all? 
In my case the submit event won't get triggered even though I'm sure it gets added to the right form.

**Comment by JelteMX** [comment]
Could you check if this [possible fixed version](https://github.com/mendix/LoginForm/blob/bugfix/passwordsave/test/widgets/LoginForm.mpk?raw=true) will work? It's a bit of a long shot. I have looked into it and come up with a possible fix. Love to hear your feedback. This version does remember my password in Firefox, in Chrome it's less stable, but that might be the test-project I'm working in. IE I haven't tested yet

**Comment by JelteMX** [comment]
Tested in IE, it asks for the password as well

**Comment by JelteMX** [comment]
Fixed in [3.4.0](https://github.com/mendix/LoginForm/releases/tag/v3.4.0), will be updated in the AppStore today
