### ISSUE TITLE
Chrome does not offer to save username / password.

### ISSUE THREAD

**Issue by rickyv3** [mendix/LoginForm#7]
Chrome does not seem to recognize that a username / password are being input, and thus does not offer to save / remember information. 

Better yet - the ability to offer a "Remember Me" option that saves both username and password would be ideal.

**Comment by Da-Dude** [comment]
Hello Ricky, 

I ran into this problem myself recently, and in order to get Chrome to recognize the fields as login fields you need "Name=Username"/"Name=Password" attributes on the Username and Password fields respectively.

I added an HTML Snippet widget that uses JavaScript with Jquery, with the following code:
jQuery(document).ready(function(){
$(".form-control.username").attr("name","Username");
$("#LoginForm_widget_LoginForm_0_password").attr("name","Password");
});

Keep in mind that this is just a temporary solution I've come up with, and it can be temperamental. For example: if you get redirected on the login via javascript, the function won't run, and you'll get inconsistent behavior.

Also I couldn't find a solution to get IE to remember passwords, if you do, please let me know.

**Comment by tieniber** [comment]
For IE10, I found [this info](https://blogs.msdn.microsoft.com/ieinternals/2009/09/10/why-wont-ie-remember-my-login-info/).

Because the widget submit the form via JS and not a standard form submit, it looks like they recommend that you call [this function](https://msdn.microsoft.com/en-us/library/Aa744113.aspx) to save form details

**Comment by mgroeneweg** [comment]
Not only in Chrome, also in Safari on iOS, rather annoying especially for mobile pages because mobile users do not want to login everytime they open the app. I tried setting the name attributes as suggested above, this did not work on iOS safari. I use LastPass on Chrome, which does recognize the login form. I double checked: when using the default login.html, all browsers ask to save the user/idpassword.

**Comment by JelteMX** [comment]
Could you check if this [possible fixed version](https://github.com/mendix/LoginForm/blob/bugfix/passwordsave/test/widgets/LoginForm.mpk?raw=true) will work? It's a bit of a long shot. I have looked into it and come up with a possible fix, I will keep @Da-Dude fix in mind (haven't tested it yet). Love to hear your feedback. This version does remember my password in Firefox, in Chrome it's less stable, but that might be the test-project I'm working in.

**Comment by JelteMX** [comment]
Tested in IE and it asks if I want to save the password as well :-)

**Comment by mgroeneweg** [comment]
It works on iOS Safari and that is where I needed it most. Also works on Chrome. Lastpass starts asking me again whether I want to save the password. Speedy Jelte rides again!

**Comment by JelteMX** [comment]
Thanks for testing. As I have tested it in IE as well, I'm confident that this fixes the other issue as well. Will be updating this widget today in the AppStore

**Comment by JelteMX** [comment]
Fixed in [3.4.0](https://github.com/mendix/LoginForm/releases/tag/v3.4.0), will be updated in the AppStore today
